# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOXVjdx3PkNwdm7hgC6TXp-ZtipwrXFR
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

url = "https://niamiaofficial.com/collections/lawn-pret?page=1"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)
print(response.url)
print(response.text[:1000])

soup = BeautifulSoup(response.text, "html.parser")

# Find all product cards
products = soup.find_all("div")

print("Total divs found:", len(products))

# Show first 20 class names
for item in products[:20]:
    print(item.get("class"))

all_divs = soup.find_all("div")

for div in all_divs:
    classes = div.get("class")

    if classes:
        joined = " ".join(classes).lower()

        if "product" in joined:
            print(classes)

all_divs = soup.find_all("div")

for div in all_divs:
    classes = div.get("class")

    if classes:
        joined = " ".join(classes).lower()

        if "product" in joined:
            print(classes)

product_cards = soup.find_all("div", class_="t4s-product")

print("Total Products Found:", len(product_cards))
print("=" * 80)

for index, item in enumerate(product_cards, start=1):
    print(f"PRODUCT {index}")
    print(item.get_text(" ", strip=True))
    print("-" * 80)

for index, product in enumerate(product_cards, start=1):
    print("=" * 100)
    print(f"PRODUCT {index}")
    print(product.prettify()[:2500])   # first 2500 chars of each product block
    print("=" * 100)

base_url = "https://niamiaofficial.com"

products = []

for product in product_cards:

    # NAME
    name_tag = product.select_one("h3.t4s-product-title a")
    name = name_tag.text.strip() if name_tag else None

    # PRICE
    price_tag = product.select_one("div.t4s-product-price")
    price = price_tag.text.strip() if price_tag else None

    # LINK
    link_tag = product.select_one("a.t4s-full-width-link")
    link = base_url + link_tag["href"] if link_tag and link_tag.get("href") else None

    products.append({
        "name": name,
        "price": price,
        "link": link
    })

# PRINT RESULTS
print("TOTAL CLEAN PRODUCTS:", len(products))
print("=" * 50)

for i, p in enumerate(products, 1):
    print(f"{i}. {p['name']} | {p['price']} | {p['link']}")

import requests
from bs4 import BeautifulSoup
import time

base_url = "https://niamiaofficial.com"
collection_url = "https://niamiaofficial.com/collections/lawn-pret?page="

all_products = []
page = 1

while True:
    print(f"Scraping page {page}...")

    url = collection_url + str(page)
    response = requests.get(url)

    if response.status_code != 200:
        print("Stopped: status code", response.status_code)
        break

    soup = BeautifulSoup(response.text, "html.parser")

    product_cards = soup.select("div.t4s-product")

    # stop condition
    if not product_cards:
        print("No more products found. Stopping.")
        break

    for product in product_cards:

        name_tag = product.select_one("h3.t4s-product-title a")
        price_tag = product.select_one("div.t4s-product-price")
        link_tag = product.select_one("a.t4s-full-width-link")

        name = name_tag.text.strip() if name_tag else None
        price = price_tag.text.strip() if price_tag else None
        link = base_url + link_tag["href"] if link_tag and link_tag.get("href") else None

        all_products.append({
            "name": name,
            "price": price,
            "link": link
        })

    page += 1
    time.sleep(1)  # ethical scraping

print("\nTOTAL PRODUCTS:", len(all_products))
for p in all_products:
    print(p)

import pandas as pd
df = pd.DataFrame(all_products)
df.to_csv("data.csv", index=False)

import requests
from bs4 import BeautifulSoup

base_url = "https://niamiaofficial.com/collections/lawn-pret?page={}"
page = 1
all_products = []

while True:
    url = base_url.format(page)
    print(f"Scraping page {page}...")

    res = requests.get(url)
    soup = BeautifulSoup(res.text, "html.parser")

    products = soup.select(".t4s-product")

    # STOP CONDITION (IMPORTANT UPGRADE)
    if len(products) == 0:
        print("No products found. Stopping.")
        break

    for p in products:
        name = p.select_one(".t4s-product-title")
        price = p.select_one(".t4s-product-price")
        link = p.select_one("a[href]")

        all_products.append({
            "name": name.text.strip() if name else None,
            "price": price.text.strip() if price else None,
            "link": "https://niamiaofficial.com" + link["href"] if link else None
        })

    page += 1