# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QDLY3byzSAxaTo4BEnQrL4Mdin7i8wf
"""

import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time
import pandas as pd

# Base URL and Headers
BASE_URL = "https://niamiaofficial.com"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

# Data storage
visited_products = set()
all_products = []
collections = set()

def get_collections():
    urls_to_check = [BASE_URL, BASE_URL + "/collections"]
    for url in urls_to_check:
        try:
            res = requests.get(url, headers=headers, timeout=10)
            if res.status_code == 200:
                soup = BeautifulSoup(res.text, "html.parser")
                for a in soup.select("a[href*='/collections/']"):
                    link = urljoin(BASE_URL, a["href"])
                    if "collections/" in link and all(x not in link for x in ["products", "all", "sort"]):
                        collections.add(link)
        except Exception as e:
            print(f"Error finding collections: {e}")
    print(f"Total Categories Found: {len(collections)}")

#  SCRAPE EACH COLLECTION


def get_clean_price(price_block):
    """Helper to extract price, strip Rs., and handle sales/ranges."""
    if not price_block:
        return "0"

    # Check if there's a specific sale tag (<ins>), otherwise get the whole block
    sale_el = price_block.select_one("ins")
    price_text = sale_el.get_text(strip=True) if sale_el else price_block.get_text(strip=True)

    # 1. Strip currency and formatting
    clean = price_text.replace("Rs.", "").replace(",", "").strip()

    # 2. If it's a range (e.g. "30000 38000"), take the first number
    # This prevents the 'smashed' numbers like 3000038000
    return clean.split()[0]

def scrape_collection(collection_url):
    page = 1
    while True:
        url = f"{collection_url}?page={page}"
        print(f"\n--- Requesting URL: {url} ---")

        try:
            res = requests.get(url, headers=headers, timeout=10)

            # Debugging Prints: Status and HTML
            print(f"Response Code: {res.status_code}")
            # Printing a snippet of HTML to ensure we aren't being blocked by a captcha
            print(f"HTML Snippet: {res.text[:300].replace('\n', ' ')}...")

            if res.status_code != 200:
                print(f"Failed to load page. Moving to next collection.")
                break

            soup = BeautifulSoup(res.text, "html.parser")
            products = soup.select(".t4s-product")

            if not products:
                print("No more products found on this page.")
                break

            new_found_count = 0
            for p in products:
                # Get Name
                name_el = p.select_one(".t4s-product-title")
                name = name_el.get_text(strip=True) if name_el else "Unknown"

                # --- THE FILTER: DROPPING PRE-ORDERS ---
                if "(pre-order)" in name.lower():
                    # Optional: uncomment the line below if you want to see what is skipped
                    # print(f"  > Skipping Pre-Order: {name}")
                    continue

                # Get Link
                link_el = p.select_one("a[href*='/products/']")
                if not link_el: continue
                full_link = urljoin(BASE_URL, link_el["href"])

                # Avoid Duplicates
                if full_link in visited_products: continue
                visited_products.add(full_link)

                # Get Unified Price
                price_block = p.select_one(".t4s-product-price")
                final_price = get_clean_price(price_block)

                all_products.append({
                    "name": name,
                    "price": final_price,
                    "link": full_link,
                    "collection": collection_url
                })
                new_found_count += 1

            print(f"Added {new_found_count} items from this page.")

            # If no items on this page passed the filter, stop paging for this collection
            if new_found_count == 0 and page > 1:
                break

            page += 1
            time.sleep(1) # Gentle delay to avoid being flagged as a bot

        except Exception as e:
            print(f"Error during request: {e}")
            break

get_collections()

for col in collections:
    scrape_collection(col)

print(f"\nScraping Finished. {len(all_products)} items found.")

if len(all_products) > 0:
    df = pd.DataFrame(all_products)

    # Convert to numeric
    df["price"] = pd.to_numeric(df["price"], errors='coerce')

    # Cleanup
    df = df.dropna(subset=['price'])
    df = df[df["price"] > 0]

    # Sort by price (Lowest to Highest) for a better CSV experience
    df = df.sort_values(by="price")

    file_name = "niamia_catalog_final.csv"
    df.to_csv(file_name, index=False, encoding="utf-8-sig")
    print(f"\nDone! CSV saved as {file_name}. Everything is clean and stripped.")

    try:
        from google.colab import files
        files.download(file_name)
    except:
        pass
else:
    print("No items found.")

